name: Mantas Group
favicon: null
layout_spectrum: 0.37523860298097134
typography_spectrum: 0.5478580077178776
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8669103351421654
  lightness: 0.3141344340983778
  saturation: 0.05090381787158549
  rhythmicContrast: 0.8732994203455746
purpose: []
